title:              Clean Blog
email:              mansoo0621@likelion.org
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://TwoShot22.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    TwoShot22
facebook_username:  Mnasoo Kim
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
