title:              만파카의 코딩 일기
email:              mansoo0621@likelion.org
description:        Handle various Development Topics
author:             Mansoo Kim
baseurl:            ""
url:                "https://TwoShot22.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    TwoShot22
facebook_username:  Mansoo Kim
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
